sudo: required
services:
  - docker

before_install:
  - docker build -t tests -f Dockerfile.dev .  

script:
  - docker run tests npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-508665931257"
  bucket-path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"  